# based on https://doc.rust-lang.org/cargo/guide/continuous-integration.html

# Setup a cache to cache job parts between jobs to ensure faster builds
cache:
  - key:
      files:
        - Cargo.lock
    paths:
      - $HOME/.cargo/
      - target/

stages:
  - cargo
  - coverage

clippy:
  stage: cargo
  image: rust:latest
  script:
    - rustup component add clippy
    - cargo clippy
test:
  stage: cargo
  image: rust:latest
  script:
    - cargo test
build:
  stage: cargo
  image: rust:latest
  script:
    - cargo build --verbose
# from https://www.collabora.com/news-and-blog/blog/2021/03/24/rust-integrating-llvm-source-base-code-coverage-with-gitlab/
coverage:
  image: "rustdocker/rust:nightly"
  stage: cargo
  variables:
    RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
    LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
  script:
    - rustup component add llvm-tools-preview
    - cargo test
    # generate html report
    - cargo install grcov
    - grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing --ignore "*cargo*" -o ./coverage/
    # generate cobertura report for gitlab integration
    - grcov . --binary-path ./target/debug/ -s . -t cobertura --branch --ignore-not-existing --ignore "*cargo*" -o coverage.xml
  artifacts:
    paths:
      - 'coverage'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
