name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features
      - run: cargo build --verbose
      - run: apt-get update
      - run: apt-get -y install graphviz
      - run: cargo test --verbose --bins --tests --features svg
